# Generated by Django 5.1.6 on 2025-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactmessage_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='hour',
            field=models.CharField(default='09:00 AM', max_length=50),
            preserve_default=False,
        ),
    ]
