# Generated by Django 5.1.6 on 2025-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_testbooking_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='test_type',
            field=models.TextField(),
        ),
    ]
