# Generated by Django 5.1.6 on 2025-03-06 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='booked_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='booked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
