# Generated by Django 5.1.6 on 2025-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_testbooking_booked_by_testbooking_booked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='labreport',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
