# Generated by Django 5.1.6 on 2025-03-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_testbooking_labreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='stage',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('report_ready', 'Report Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
